volumes:
    media: {}
    static: {}
    db: {}
    redis_db: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:16.3-alpine
        restart: always
        volumes:
          - db:/var/lib/postgresql/data
        env_file:
            - .env

    redis:
        container_name: ${PROJECT_NAME}-redis
        image: redis:7.2-alpine
        restart: always
        volumes:
            - redis_db:/data

    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        restart: always
        command: sh runserver.sh 4
        volumes: 
            - ./backend:/backend
            - media:/var/www/media/
            - static:/var/www/static/
        env_file: 
            - .env

    nginx:
        container_name: ${PROJECT_NAME}-nginx
        image: nginx:1.25.2-alpine
        restart: always
        ports:
            - 8000:8000
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
            - media:/var/www/media/
            - static:/var/www/static/
        env_file:
            - .env
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
    
    celery:
        container_name: ${PROJECT_NAME}-celery_worker
        build: ./backend
        restart: always
        command: celery -A backend worker --loglevel=info
        volumes:
            - ./backend:/backend
        env_file: 
            - .env

    celery-beat:
        container_name: ${PROJECT_NAME}-celery_beat
        build: ./backend
        restart: always
        command: celery -A backend beat --loglevel=info
        volumes:
            - ./backend:/backend
        env_file: 
            - .env