# Generated by Django 5.1.1 on 2024-10-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('is_healthy', models.BooleanField(default=False)),
                ('log', models.TextField(default='-')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcheck.project')),
            ],
        ),
    ]
