# Generated by Django 5.1.1 on 2024-10-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
