# Generated by Django 5.1.1 on 2026-04-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcheck", "0002_url_is_use_url_notify"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheckResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked_at", models.DateTimeField()),
                ("is_healthy", models.BooleanField()),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("log", models.TextField(default="-")),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_check_results",
                        to="healthcheck.url",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at", "-id"],
            },
        ),
    ]
