# Generated by Django 5.1.1 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcheck", "0003_healthcheckresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcheckresult",
            name="checked_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
