# Generated by Django 5.1.1 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcheck", "0004_healthcheckresult_checked_at_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="tag",
            field=models.CharField(blank=True, db_index=True, default="", max_length=50),
        ),
    ]
