log_format custom_log_format '$time_iso8601 '
                              '"$request" $status $body_bytes_sent '
                              '"$http_referer" "$http_user_agent" "$upstream_http_x_username" "$upstream_http_x_error"';

upstream backend {
    server backend:8000;
}

server {
    listen 8000;
    listen [::]:8000;

    server_name _;

    proxy_buffer_size   128k;
    proxy_buffers   4 256k;
    proxy_busy_buffers_size   256k;
    client_max_body_size 100M;

    location / {
        proxy_pass http://backend/;
        proxy_set_header Host $http_host;
        
        # Include the log information header X-Username & X-Error
        proxy_set_header X-Username $upstream_http_x_username;
        proxy_set_header X-Error $upstream_http_x_error;
    }

    location /static/ {
        autoindex on;
        alias /var/www/static/;
        access_log on;
    }

    location /media/ {
        alias /var/www/media/;
        access_log off;
    }
}